### ISSUE TITLE
No such a file or directory

### ISSUE THREAD

**Issue by MCSH** [fmvilas/swagger-node-codegen#10]
Running `snc` for the first time, I always got the following error:
`/usr/bin/env: ‘node --trace-deprecation’: No such file or directory`

After banging my head on the wall for a couple of times, I realized the problem is the shebang on the main file. temporarily removing the flag fixed the issue for me, but that is not a real solution. What could be done?

Thanks in advance!

**Comment by fmvilas** [comment]
Hey, thanks for reporting. By flag you mean the `--trace-deprecation` flag? It's ok to remove it, I just forgot it there after debugging 😌

**Comment by fmvilas** [comment]
Version 1.0.1 is now fixing this problem. You can already update using npm. Thanks for reporting!

**Comment by MCSH** [comment]
Thank you for solving this so quick!
