### ISSUE TITLE
Service Template Should Return Status rather than Code

### ISSUE THREAD

**Issue by stnguyen90** [fmvilas/swagger-node-codegen#17]
https://github.com/fmvilas/swagger-node-codegen/blob/603511c202f41224832fbef89a4f11199faddfd7/templates/express-server/src/api/services/___.js#L33

`code` should be `status` as the comments and routes expect the `status` property.

**Comment by fmvilas** [comment]
Thanks for the fix @stnguyen90. I'm closing the issue. Feel free to keep commenting here.
