### ISSUE TITLE
OpenAPI v3: Not properly supported

### ISSUE THREAD

**Issue by mwillbanks** [fmvilas/swagger-node-codegen#19]
The first thing that I found when attempting to generate from an openapi v3 specification is that it is following v2 swagger rules where it looks for a basepath vs. using the new server directive.  See: https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by mwillbanks** [comment]
Seems I must have had a bad version installed; sorry for the noise!

**Comment by fmvilas** [comment]
Thanks for taking the time to report it anyway, @mwillbanks.
