### ISSUE TITLE
Custom handlebar helpers

### ISSUE THREAD

**Issue by guided1** [fmvilas/swagger-node-codegen#29]
Hi,
I'd like to be able to create and include helper for handlebars not in the library. Do you have a preference of how you want to achieve this?

I was thinking of using a parameter supplying another parameter:

-b, --handlebars                     path to external handlebars helpers file

This would then include the file if the path is valid and it exists.

Thoughts?

I'll put in a pull request if you agree

**Comment by fmvilas** [comment]
That'd be awesome! Could you provide a PR?

**Comment by guided1** [comment]
Sure thing. https://github.com/fmvilas/swagger-node-codegen/pull/30

**Comment by fmvilas** [comment]
I'm closing this issue since #30 has been merged.

**Comment by fmvilas** [comment]
I just did a release and published to npm: https://github.com/fmvilas/swagger-node-codegen/releases/tag/1.3.0.
