### ISSUE TITLE
Creating a new version

### ISSUE THREAD

**Issue by RaduFurnea** [fmvilas/swagger-node-codegen#42]
Is there a way to update the folder after specification edit or addition without deleting the entire server and rewriting the endpoint implementations?

**Comment by fmvilas** [comment]
Hi @RaduFurnea. Currently, this is not possible, but I do see the value. Would you like to implement it?

**Comment by RaduFurnea** [comment]
Hi, thanks for getting back so quickly. Unfortunately I have no spare time these days but I'll put it on my to-do list and have a look. Will make a PR when the time comes. Thanks!
