### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: req is not defined

### ISSUE THREAD

**Issue by kloener** [fmvilas/swagger-node-codegen#48]
Hi,

I get an error when I generate a simple REST endpoint, because the variable "req" cannot be found correctly.

Affected File: https://github.com/fmvilas/swagger-node-codegen/blob/a884246059f3207da58be5a58c4c1a17f4e0313c/templates/express-server/src/api/routes/___.js#L62

I guess "reqtest" should be named to "req" instead.

Kind regards, Christian

**Comment by fmvilas** [comment]
You're right. This looks like a typo. Would you mind opening a PR?

**Comment by kloener** [comment]
Tested it with theses PR changes and it works :-)

**Comment by fmvilas** [comment]
It's already on npm, version 1.6.2. Thanks!
